Traceback (most recent call last):
  File "C:\Users\Freyja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Freyja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Freyja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Freyja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Freyja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Freyja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Freyja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for index, row in student_assessment.iterrows():
    NaN_students_all_exams = NaN_students_all_exams.append(student_assessment.loc[student_info['id_student'] == row['id_student']])
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexingError[0m                             Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_21832/4105479180.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mfor[0m [0mindex[0m[1;33m,[0m [0mrow[0m [1;32min[0m [0mstudent_assessment[0m[1;33m.[0m[0miterrows[0m[1;33m([0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m     [0mNaN_students_all_exams[0m [1;33m=[0m [0mNaN_students_all_exams[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mstudent_assessment[0m[1;33m.[0m[0mloc[0m[1;33m[[0m[0mstudent_info[0m[1;33m[[0m[1;34m'id_student'[0m[1;33m][0m [1;33m==[0m [0mrow[0m[1;33m[[0m[1;34m'id_student'[0m[1;33m][0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexing.py[0m in [0;36m__getitem__[1;34m(self, key)[0m
[0;32m    929[0m [1;33m[0m[0m
[0;32m    930[0m             [0mmaybe_callable[0m [1;33m=[0m [0mcom[0m[1;33m.[0m[0mapply_if_callable[0m[1;33m([0m[0mkey[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mobj[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 931[1;33m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_getitem_axis[0m[1;33m([0m[0mmaybe_callable[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    932[0m [1;33m[0m[0m
[0;32m    933[0m     [1;32mdef[0m [0m_is_scalar_access[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mkey[0m[1;33m:[0m [0mtuple[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexing.py[0m in [0;36m_getitem_axis[1;34m(self, key, axis)[0m
[0;32m   1142[0m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_get_slice_axis[0m[1;33m([0m[0mkey[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1143[0m         [1;32melif[0m [0mcom[0m[1;33m.[0m[0mis_bool_indexer[0m[1;33m([0m[0mkey[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1144[1;33m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_getbool_axis[0m[1;33m([0m[0mkey[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1145[0m         [1;32melif[0m [0mis_list_like_indexer[0m[1;33m([0m[0mkey[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1146[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexing.py[0m in [0;36m_getbool_axis[1;34m(self, key, axis)[0m
[0;32m    946[0m         [1;31m# caller is responsible for ensuring non-None axis[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m    947[0m         [0mlabels[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mobj[0m[1;33m.[0m[0m_get_axis[0m[1;33m([0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 948[1;33m         [0mkey[0m [1;33m=[0m [0mcheck_bool_indexer[0m[1;33m([0m[0mlabels[0m[1;33m,[0m [0mkey[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    949[0m         [0minds[0m [1;33m=[0m [0mkey[0m[1;33m.[0m[0mnonzero[0m[1;33m([0m[1;33m)[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    950[0m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mobj[0m[1;33m.[0m[0m_take_with_is_copy[0m[1;33m([0m[0minds[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexing.py[0m in [0;36mcheck_bool_indexer[1;34m(index, key)[0m
[0;32m   2386[0m         [0mmask[0m [1;33m=[0m [0misna[0m[1;33m([0m[0mresult[0m[1;33m.[0m[0m_values[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2387[0m         [1;32mif[0m [0mmask[0m[1;33m.[0m[0many[0m[1;33m([0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2388[1;33m             raise IndexingError(
[0m[0;32m   2389[0m                 [1;34m"Unalignable boolean Series provided as "[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2390[0m                 [1;34m"indexer (index of the boolean Series and of "[0m[1;33m[0m[1;33m[0m[0m

[1;31mIndexingError[0m: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

